### ISSUE TITLE
Meta with string 1 should not be considered as booleans

### ISSUE THREAD

**Issue by jriouovh** [wilfriedroset/consul-awx#7]
Hello,

We have a Consul agent running on servers with `{"cluster": "integer"}` node meta creating `cluster_integer` groups. But when the integer is "1", the lib detects a boolean, creating a `cluster` group instead of `cluster_1`.

I think meta with integer 1 should not be considered as booleans.

**Comment by wilfriedroset** [comment]
I reckon this change comes from #5, we should discuss this with @klevron1 to not break his usecases.
In the mean time could you try `{"cluster": "str"}` it should produce the expected output as per the following test
https://github.com/wilfriedroset/consul-awx/blob/419e3ecb9e19bd715f3d59aef79c4894a5daf9dc/consul_awx_test.py#L96

**Comment by jriouovh** [comment]
Tested with `CONSUL_NODE_META_TYPES='{"cluster":"int"}'` environment variable with success!
